### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by hxiaoj** [SooLab/Part2Object#1]
when I run "python vccs/data_prepare_ScanNet.py --data_path "PATH_TO_RAW_SCANNET_DATASET" ", the error "ModuleNotFoundError: No module named 'lib'" happened

**Comment by zhangyl4** [comment]
Thank you for your question. We follow the point cloud initialization method from the work [GrowSP](https://github.com/vLAR-group/GrowSP). If you are encountering a "ModuleNotFoundError: No module named 'lib'" error, it is likely due to missing environment dependencies. Please refer to the environment setup instructions provided in that repository to complete the necessary installations. 
We appreciate your feedback and will update the installation process in our README shortly.


> when I run "python vccs/data_prepare_ScanNet.py --data_path "PATH_TO_RAW_SCANNET_DATASET" ", the error "ModuleNotFoundError: No module named 'lib'" happened
